In [ ]:
from transformers import pipeline

In [ ]:
image_to_text = pipeline("image-to-text", model="nlpconnect/vit-gpt2-image-captioning")

Could not find image processor class in the image processor config or the model config. Loading based on pattern matching with the model's feature extractor configuration.
/usr/local/lib/python3.10/dist-packages/transformers/models/vit/feature_extraction_vit.py:28: FutureWarning: The class ViTFeatureExtractor is deprecated and will be removed in version 5 of Transformers. Please use ViTImageProcessor instead.
  warnings.warn(

In [ ]:
caption = image_to_text("/content/sample_image.jpg")[0]['generated_text']

In [ ]:
print(caption)

a woman is sitting at a table with two men

# Emoji

In [ ]:
!unzip /content/drive/MyDrive/Project/emoji/emojify.zip

Archive:  /content/drive/MyDrive/Project/emoji/emojify.zip
replace emojify_data.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: ㅛ
error:  invalid response [ㅛ]
replace emojify_data.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: ㅛ
error:  invalid response [ㅛ]
replace emojify_data.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: emojify_data.csv
replace test_emoji.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: test_emoji.csv
replace train_emoji.csv? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: train_emoji.csv

In [ ]:
!unzip /content/drive/MyDrive/Project/emoji/glove.zip

Archive:  /content/drive/MyDrive/Project/emoji/glove.zip
replace glove.6B.50d.txt? [y]es, [n]o, [A]ll, [N]one, [r]ename: y
  inflating: glove.6B.50d.txt

In [ ]:
!pip install emoji

Requirement already satisfied: emoji in /usr/local/lib/python3.10/dist-packages (2.9.0)

In [ ]:
import emoji
import numpy as np
import pandas as pd

## Text Preprocessing using Embeddings

In [ ]:
glove_file = open("/content/glove.6B.50d.txt", encoding = 'utf8')

In [ ]:
def intialize_emb_matrix(file):
    embedding_matrix = {}
    for line in file:
        values = line.split()
        word = values[0]
        embedding = np.array(values[1:], dtype='float64')
        embedding_matrix[word] = embedding

    return embedding_matrix

In [ ]:
embedding_matrix = intialize_emb_matrix(glove_file)

In [ ]:
embedding_matrix['dance']

array([-9.9716e-01,  6.1348e-01, -1.7686e+00,  8.7052e-02, -2.4644e-01,
        1.9984e-01, -2.5892e-01, -3.1309e-02, -4.3117e-01,  1.0844e+00,
        4.7032e-01, -3.6731e-01,  1.0047e-01,  1.2459e+00,  2.5728e-03,
       -3.8805e-01,  4.8489e-01,  3.8052e-01, -5.6983e-01, -8.4332e-01,
        8.8607e-01,  9.7396e-01,  9.0600e-03,  9.5187e-01,  3.3867e-01,
       -2.5218e-01, -1.5633e+00, -4.8921e-01, -3.4712e-01, -1.2629e+00,
        2.8455e+00,  2.8887e-01, -1.9158e-01,  6.5195e-02, -1.9799e-01,
        2.2815e-01,  4.4613e-01, -8.2659e-02, -3.3068e-01,  4.8144e-02,
       -2.7224e-01, -2.1765e-01, -5.5931e-01, -4.0149e-01,  5.6395e-01,
       -1.9915e-01,  7.2645e-01, -1.5184e+00, -8.7863e-01,  2.1860e-01])

In [ ]:
embedding_matrix['dance'].shape

(50,)

In [ ]:
def get_emb_data(data, max_len):
#     max_len = 168
    embedding_data = np.zeros((len(data), max_len, 50))  # from glove6B50d

    for idx in range(data.shape[0]):
        words_in_sentence = data[idx].split()

        for i in range(len(words_in_sentence)):
            if embedding_matrix.get(words_in_sentence[i].lower()) is not None:
                embedding_data[idx][i] = embedding_matrix[words_in_sentence[i].lower()]

    return embedding_data

## emoji dataset

In [ ]:
train_data = pd.read_csv("/content/train_emoji.csv", header=None)
test_data = pd.read_csv("/content/test_emoji.csv", header=None)

In [ ]:
train_data.head()

                                 0  1   2     3
0           never talk to me again  3 NaN   NaN
1  I am proud of your achievements  2 NaN   NaN
2   It is the worst day in my life  3 NaN   NaN
3                 Miss you so much  0 NaN   [0]
4                     food is life  4 NaN   NaN

In [ ]:
test_data.head()

                             0  1
0              I want to eat\t  4
1          he did not answer\t  3
2   he got a very nice raise\t  2
3  she got me a nice present\t  2
4   ha ha ha it was so funny\t  2

In [ ]:
emoji.emojize(':angry_face:')

'😠'

In [ ]:
emoji_mapping = {
    '0': ':beating_heart:',
    '1': ':baseball:',
    '2': ':beaming_face_with_smiling_eyes:',
    '3': ':angry_face:',
    '4': ':face_savoring_food:'
}

In [ ]:
for key, value in emoji_mapping.items():
    emoji_mapping[key] = emoji.emojize(value)

print(emoji_mapping)

{'0': '💓', '1': '⚾', '2': '😁', '3': '😠', '4': '😋'}

In [ ]:
X_train = train_data[0].values
y_train = train_data[1].values

In [ ]:
X_train = get_emb_data(X_train, 10)

In [ ]:
X_train

array([[[ 9.5387e-02, -1.6865e-01, -1.1514e-01, ..., -4.2103e-01,
         -5.3817e-01,  1.3738e-01],
        [-3.4604e-02,  4.1087e-01, -9.7368e-02, ...,  5.6204e-01,
         -5.9770e-01,  9.5068e-01],
        [ 6.8047e-01, -3.9263e-02,  3.0186e-01, ..., -7.3297e-02,
         -6.4699e-02, -2.6044e-01],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00, ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00, ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00, ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]],

       [[ 1.1891e-01,  1.5255e-01, -8.2073e-02, ..., -5.7512e-01,
         -2.6671e-01,  9.2121e-01],
        [ 3.4664e-01,  3.9805e-01,  4.8970e-01, ...,  8.6576e-02,
          3.4037e-01,  1.3588e+00],
        [-5.9180e-01,  2.7671e-01, -4.6971e-01, ..., -2.0055e-01,
         -2.6487e-01,  5.7981e-01],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00, ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00, ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00, ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]],

       [[ 6.1183e-01, -2.2072e-01, -1.0898e-01, ..., -4.3688e-02,
         -9.7922e-02,  1.6806e-01],
        [ 6.1850e-01,  6.4254e-01, -4.6552e-01, ..., -2.7557e-01,
          3.0899e-01,  4.8497e-01],
        [ 4.1800e-01,  2.4968e-01, -4.1242e-01, ..., -1.8411e-01,
         -1.1514e-01, -7.8581e-01],
        ...,
        [ 5.1491e-01,  8.8806e-01, -7.1906e-01, ..., -9.9837e-01,
         -6.6328e-02,  1.3118e-01],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00, ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00, ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]],

       ...,

       [[ 4.5323e-01,  5.9811e-02, -1.0577e-01, ...,  5.3240e-01,
         -2.5103e-01,  6.2546e-01],
        [ 6.1850e-01,  6.4254e-01, -4.6552e-01, ..., -2.7557e-01,
          3.0899e-01,  4.8497e-01],
        [ 1.3423e-01, -7.0572e-01,  2.5652e-01, ...,  4.3723e-01,
          9.0636e-01,  5.1193e-01],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00, ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00, ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00, ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]],

       [[ 1.1891e-01,  1.5255e-01, -8.2073e-02, ..., -5.7512e-01,
         -2.6671e-01,  9.2121e-01],
        [-1.3886e-01,  1.1401e+00, -8.5212e-01, ..., -1.3711e+00,
         -2.8606e-01,  2.8980e-01],
        [-1.0919e-03,  3.3324e-01,  3.5743e-01, ..., -4.5697e-01,
         -4.8969e-02,  1.1316e+00],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00, ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00, ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00, ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]],

       [[-2.6567e-02,  1.3357e+00, -1.0280e+00, ..., -4.9658e-01,
         -4.1618e-01, -2.5490e-01],
        [-2.0343e-01, -4.5235e-02,  2.3346e-01, ...,  7.8093e-01,
          4.6384e-03,  1.3011e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00, ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        ...,
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00, ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00, ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00, ...,  0.0000e+00,
          0.0000e+00,  0.0000e+00]]])

In [ ]:
import keras
from keras.models import Sequential
from keras.layers import LSTM, SimpleRNN, Dense, Dropout

In [ ]:
from keras.utils import to_categorical

In [ ]:
y_train = to_categorical(y_train)
y_train

array([[0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.]], dtype=float32)

In [ ]:
model_tte = Sequential()
model_tte.add(LSTM(units=64, input_shape=(10, 50), return_sequences=True))
model_tte.add(Dropout(0.3))
model_tte.add(LSTM(units=32))
model_tte.add(Dropout(0.2))
model_tte.add(Dense(units=10, activation='relu'))
model_tte.add(Dense(units=5, activation='softmax'))

In [ ]:
model_tte.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 lstm_6 (LSTM)               (None, 10, 64)            29440

 dropout_6 (Dropout)         (None, 10, 64)            0

 lstm_7 (LSTM)               (None, 32)                12416

 dropout_7 (Dropout)         (None, 32)                0

 dense_8 (Dense)             (None, 10)                330

 dense_9 (Dense)             (None, 5)                 55

=================================================================
Total params: 42241 (165.00 KB)
Trainable params: 42241 (165.00 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [ ]:
model_tte.compile(optimizer='adam', loss=keras.losses.categorical_crossentropy, metrics=['acc'])

In [ ]:
history = model_tte.fit(X_train, y_train, validation_split=0.1, verbose=2, batch_size=32, epochs=100)

Epoch 1/100
4/4 - 4s - loss: 1.5864 - acc: 0.2203 - val_loss: 1.6159 - val_acc: 0.0714 - 4s/epoch - 998ms/step
Epoch 2/100
4/4 - 0s - loss: 1.5244 - acc: 0.3814 - val_loss: 1.6406 - val_acc: 0.0714 - 109ms/epoch - 27ms/step
Epoch 3/100
4/4 - 0s - loss: 1.5051 - acc: 0.3136 - val_loss: 1.6758 - val_acc: 0.0714 - 95ms/epoch - 24ms/step
Epoch 4/100
4/4 - 0s - loss: 1.4555 - acc: 0.3644 - val_loss: 1.6571 - val_acc: 0.1429 - 100ms/epoch - 25ms/step
Epoch 5/100
4/4 - 0s - loss: 1.4369 - acc: 0.3644 - val_loss: 1.5896 - val_acc: 0.1429 - 113ms/epoch - 28ms/step
Epoch 6/100
4/4 - 0s - loss: 1.3905 - acc: 0.4576 - val_loss: 1.5366 - val_acc: 0.2143 - 123ms/epoch - 31ms/step
Epoch 7/100
4/4 - 0s - loss: 1.3485 - acc: 0.4068 - val_loss: 1.5823 - val_acc: 0.2143 - 89ms/epoch - 22ms/step
Epoch 8/100
4/4 - 0s - loss: 1.3022 - acc: 0.4153 - val_loss: 1.5330 - val_acc: 0.2857 - 83ms/epoch - 21ms/step
Epoch 9/100
4/4 - 0s - loss: 1.2664 - acc: 0.4492 - val_loss: 1.5187 - val_acc: 0.2143 - 82ms/epoch - 20ms/step
Epoch 10/100
4/4 - 0s - loss: 1.2186 - acc: 0.4661 - val_loss: 1.5534 - val_acc: 0.1429 - 118ms/epoch - 30ms/step
Epoch 11/100
4/4 - 0s - loss: 1.1490 - acc: 0.4915 - val_loss: 1.6497 - val_acc: 0.1429 - 120ms/epoch - 30ms/step
Epoch 12/100
4/4 - 0s - loss: 1.1050 - acc: 0.5339 - val_loss: 1.3946 - val_acc: 0.4286 - 93ms/epoch - 23ms/step
Epoch 13/100
4/4 - 0s - loss: 1.0702 - acc: 0.5593 - val_loss: 1.5395 - val_acc: 0.3571 - 89ms/epoch - 22ms/step
Epoch 14/100
4/4 - 0s - loss: 1.0413 - acc: 0.5508 - val_loss: 1.3345 - val_acc: 0.5714 - 86ms/epoch - 21ms/step
Epoch 15/100
4/4 - 0s - loss: 0.9662 - acc: 0.6017 - val_loss: 1.4003 - val_acc: 0.5000 - 93ms/epoch - 23ms/step
Epoch 16/100
4/4 - 0s - loss: 0.9042 - acc: 0.6610 - val_loss: 1.2475 - val_acc: 0.5714 - 84ms/epoch - 21ms/step
Epoch 17/100
4/4 - 0s - loss: 0.9117 - acc: 0.6102 - val_loss: 1.4121 - val_acc: 0.5000 - 108ms/epoch - 27ms/step
Epoch 18/100
4/4 - 0s - loss: 0.8359 - acc: 0.6949 - val_loss: 1.1519 - val_acc: 0.5714 - 95ms/epoch - 24ms/step
Epoch 19/100
4/4 - 0s - loss: 0.7441 - acc: 0.7203 - val_loss: 1.3813 - val_acc: 0.5000 - 95ms/epoch - 24ms/step
Epoch 20/100
4/4 - 0s - loss: 0.7267 - acc: 0.6949 - val_loss: 1.2215 - val_acc: 0.5000 - 104ms/epoch - 26ms/step
Epoch 21/100
4/4 - 0s - loss: 0.6644 - acc: 0.7458 - val_loss: 1.5148 - val_acc: 0.4286 - 98ms/epoch - 24ms/step
Epoch 22/100
4/4 - 0s - loss: 0.6231 - acc: 0.7373 - val_loss: 1.2829 - val_acc: 0.5000 - 121ms/epoch - 30ms/step
Epoch 23/100
4/4 - 0s - loss: 0.5809 - acc: 0.7712 - val_loss: 1.6918 - val_acc: 0.4286 - 105ms/epoch - 26ms/step
Epoch 24/100
4/4 - 0s - loss: 0.6028 - acc: 0.7627 - val_loss: 1.0751 - val_acc: 0.5714 - 103ms/epoch - 26ms/step
Epoch 25/100
4/4 - 0s - loss: 0.6158 - acc: 0.7797 - val_loss: 1.5569 - val_acc: 0.5714 - 109ms/epoch - 27ms/step
Epoch 26/100
4/4 - 0s - loss: 0.6719 - acc: 0.7542 - val_loss: 1.3157 - val_acc: 0.5000 - 161ms/epoch - 40ms/step
Epoch 27/100
4/4 - 0s - loss: 0.6247 - acc: 0.7966 - val_loss: 1.0897 - val_acc: 0.5000 - 139ms/epoch - 35ms/step
Epoch 28/100
4/4 - 0s - loss: 0.5239 - acc: 0.8136 - val_loss: 1.9625 - val_acc: 0.4286 - 102ms/epoch - 25ms/step
Epoch 29/100
4/4 - 0s - loss: 0.5396 - acc: 0.7881 - val_loss: 1.2493 - val_acc: 0.5000 - 82ms/epoch - 20ms/step
Epoch 30/100
4/4 - 0s - loss: 0.5034 - acc: 0.8475 - val_loss: 0.9015 - val_acc: 0.6429 - 117ms/epoch - 29ms/step
Epoch 31/100
4/4 - 0s - loss: 0.5193 - acc: 0.7966 - val_loss: 1.2169 - val_acc: 0.5714 - 91ms/epoch - 23ms/step
Epoch 32/100
4/4 - 0s - loss: 0.4841 - acc: 0.8220 - val_loss: 1.4710 - val_acc: 0.5000 - 107ms/epoch - 27ms/step
Epoch 33/100
4/4 - 0s - loss: 0.4412 - acc: 0.8475 - val_loss: 1.0903 - val_acc: 0.5714 - 98ms/epoch - 25ms/step
Epoch 34/100
4/4 - 0s - loss: 0.4012 - acc: 0.8898 - val_loss: 0.9383 - val_acc: 0.5714 - 139ms/epoch - 35ms/step
Epoch 35/100
4/4 - 0s - loss: 0.3725 - acc: 0.8898 - val_loss: 1.1025 - val_acc: 0.5714 - 88ms/epoch - 22ms/step
Epoch 36/100
4/4 - 0s - loss: 0.3569 - acc: 0.8814 - val_loss: 1.3740 - val_acc: 0.5714 - 146ms/epoch - 36ms/step
Epoch 37/100
4/4 - 0s - loss: 0.3395 - acc: 0.8983 - val_loss: 1.5412 - val_acc: 0.5714 - 103ms/epoch - 26ms/step
Epoch 38/100
4/4 - 0s - loss: 0.3031 - acc: 0.9068 - val_loss: 1.0883 - val_acc: 0.5714 - 84ms/epoch - 21ms/step
Epoch 39/100
4/4 - 0s - loss: 0.2979 - acc: 0.9153 - val_loss: 1.0448 - val_acc: 0.6429 - 120ms/epoch - 30ms/step
Epoch 40/100
4/4 - 0s - loss: 0.2878 - acc: 0.9237 - val_loss: 1.3098 - val_acc: 0.6429 - 108ms/epoch - 27ms/step
Epoch 41/100
4/4 - 0s - loss: 0.2536 - acc: 0.9322 - val_loss: 1.7459 - val_acc: 0.6429 - 158ms/epoch - 39ms/step
Epoch 42/100
4/4 - 0s - loss: 0.2542 - acc: 0.9153 - val_loss: 1.5570 - val_acc: 0.6429 - 82ms/epoch - 20ms/step
Epoch 43/100
4/4 - 0s - loss: 0.2288 - acc: 0.9576 - val_loss: 0.9239 - val_acc: 0.6429 - 81ms/epoch - 20ms/step
Epoch 44/100
4/4 - 0s - loss: 0.2265 - acc: 0.9576 - val_loss: 1.0301 - val_acc: 0.5714 - 88ms/epoch - 22ms/step
Epoch 45/100
4/4 - 0s - loss: 0.1900 - acc: 0.9661 - val_loss: 1.5595 - val_acc: 0.5714 - 116ms/epoch - 29ms/step
Epoch 46/100
4/4 - 0s - loss: 0.2201 - acc: 0.9492 - val_loss: 1.4069 - val_acc: 0.5714 - 85ms/epoch - 21ms/step
Epoch 47/100
4/4 - 0s - loss: 0.1585 - acc: 0.9915 - val_loss: 0.8180 - val_acc: 0.7143 - 131ms/epoch - 33ms/step
Epoch 48/100
4/4 - 0s - loss: 0.1814 - acc: 0.9661 - val_loss: 1.7825 - val_acc: 0.5000 - 93ms/epoch - 23ms/step
Epoch 49/100
4/4 - 0s - loss: 0.1779 - acc: 0.9576 - val_loss: 1.3557 - val_acc: 0.5714 - 84ms/epoch - 21ms/step
Epoch 50/100
4/4 - 0s - loss: 0.1361 - acc: 0.9831 - val_loss: 0.7888 - val_acc: 0.7143 - 86ms/epoch - 21ms/step
Epoch 51/100
4/4 - 0s - loss: 0.1571 - acc: 0.9576 - val_loss: 0.9891 - val_acc: 0.5714 - 103ms/epoch - 26ms/step
Epoch 52/100
4/4 - 0s - loss: 0.1697 - acc: 0.9661 - val_loss: 1.5587 - val_acc: 0.5714 - 131ms/epoch - 33ms/step
Epoch 53/100
4/4 - 0s - loss: 0.1637 - acc: 0.9576 - val_loss: 0.9803 - val_acc: 0.6429 - 107ms/epoch - 27ms/step
Epoch 54/100
4/4 - 0s - loss: 0.1005 - acc: 1.0000 - val_loss: 1.0149 - val_acc: 0.6429 - 134ms/epoch - 33ms/step
Epoch 55/100
4/4 - 0s - loss: 0.1605 - acc: 0.9661 - val_loss: 0.9415 - val_acc: 0.7143 - 84ms/epoch - 21ms/step
Epoch 56/100
4/4 - 0s - loss: 0.2099 - acc: 0.9237 - val_loss: 1.0076 - val_acc: 0.5714 - 83ms/epoch - 21ms/step
Epoch 57/100
4/4 - 0s - loss: 0.3314 - acc: 0.9068 - val_loss: 1.6739 - val_acc: 0.5714 - 80ms/epoch - 20ms/step
Epoch 58/100
4/4 - 0s - loss: 0.2018 - acc: 0.9407 - val_loss: 0.5471 - val_acc: 0.7857 - 92ms/epoch - 23ms/step
Epoch 59/100
4/4 - 0s - loss: 0.3031 - acc: 0.8559 - val_loss: 1.1779 - val_acc: 0.6429 - 84ms/epoch - 21ms/step
Epoch 60/100
4/4 - 0s - loss: 0.2294 - acc: 0.9576 - val_loss: 2.5533 - val_acc: 0.5000 - 127ms/epoch - 32ms/step
Epoch 61/100
4/4 - 0s - loss: 0.1559 - acc: 0.9492 - val_loss: 1.0236 - val_acc: 0.5714 - 92ms/epoch - 23ms/step
Epoch 62/100
4/4 - 0s - loss: 0.1208 - acc: 0.9746 - val_loss: 0.7847 - val_acc: 0.7143 - 76ms/epoch - 19ms/step
Epoch 63/100
4/4 - 0s - loss: 0.0874 - acc: 0.9915 - val_loss: 1.3694 - val_acc: 0.5714 - 85ms/epoch - 21ms/step
Epoch 64/100
4/4 - 0s - loss: 0.0667 - acc: 1.0000 - val_loss: 1.8312 - val_acc: 0.5714 - 136ms/epoch - 34ms/step
Epoch 65/100
4/4 - 0s - loss: 0.0821 - acc: 0.9915 - val_loss: 1.8771 - val_acc: 0.5714 - 94ms/epoch - 23ms/step
Epoch 66/100
4/4 - 0s - loss: 0.0687 - acc: 1.0000 - val_loss: 1.6464 - val_acc: 0.5714 - 167ms/epoch - 42ms/step
Epoch 67/100
4/4 - 0s - loss: 0.0553 - acc: 1.0000 - val_loss: 1.3034 - val_acc: 0.6429 - 183ms/epoch - 46ms/step
Epoch 68/100
4/4 - 0s - loss: 0.0607 - acc: 0.9915 - val_loss: 1.0108 - val_acc: 0.7143 - 247ms/epoch - 62ms/step
Epoch 69/100
4/4 - 0s - loss: 0.0606 - acc: 1.0000 - val_loss: 1.3819 - val_acc: 0.5714 - 217ms/epoch - 54ms/step
Epoch 70/100
4/4 - 0s - loss: 0.0475 - acc: 1.0000 - val_loss: 1.7766 - val_acc: 0.5714 - 169ms/epoch - 42ms/step
Epoch 71/100
4/4 - 0s - loss: 0.0570 - acc: 0.9915 - val_loss: 1.5981 - val_acc: 0.5714 - 159ms/epoch - 40ms/step
Epoch 72/100
4/4 - 0s - loss: 0.0503 - acc: 1.0000 - val_loss: 1.3828 - val_acc: 0.6429 - 160ms/epoch - 40ms/step
Epoch 73/100
4/4 - 0s - loss: 0.0429 - acc: 1.0000 - val_loss: 1.2825 - val_acc: 0.5714 - 209ms/epoch - 52ms/step
Epoch 74/100
4/4 - 0s - loss: 0.0544 - acc: 0.9915 - val_loss: 1.2706 - val_acc: 0.6429 - 231ms/epoch - 58ms/step
Epoch 75/100
4/4 - 0s - loss: 0.0364 - acc: 1.0000 - val_loss: 1.3864 - val_acc: 0.6429 - 126ms/epoch - 32ms/step
Epoch 76/100
4/4 - 0s - loss: 0.0390 - acc: 1.0000 - val_loss: 1.5370 - val_acc: 0.6429 - 166ms/epoch - 41ms/step
Epoch 77/100
4/4 - 0s - loss: 0.0329 - acc: 1.0000 - val_loss: 1.5727 - val_acc: 0.6429 - 158ms/epoch - 39ms/step
Epoch 78/100
4/4 - 0s - loss: 0.0329 - acc: 1.0000 - val_loss: 1.5572 - val_acc: 0.5714 - 240ms/epoch - 60ms/step
Epoch 79/100
4/4 - 0s - loss: 0.0328 - acc: 1.0000 - val_loss: 1.5654 - val_acc: 0.5714 - 158ms/epoch - 39ms/step
Epoch 80/100
4/4 - 0s - loss: 0.0301 - acc: 1.0000 - val_loss: 1.7500 - val_acc: 0.5714 - 112ms/epoch - 28ms/step
Epoch 81/100
4/4 - 0s - loss: 0.0363 - acc: 0.9915 - val_loss: 1.6251 - val_acc: 0.5714 - 96ms/epoch - 24ms/step
Epoch 82/100
4/4 - 0s - loss: 0.0244 - acc: 1.0000 - val_loss: 1.4865 - val_acc: 0.5714 - 118ms/epoch - 30ms/step
Epoch 83/100
4/4 - 0s - loss: 0.0278 - acc: 1.0000 - val_loss: 1.4475 - val_acc: 0.6429 - 93ms/epoch - 23ms/step
Epoch 84/100
4/4 - 0s - loss: 0.0228 - acc: 1.0000 - val_loss: 1.4659 - val_acc: 0.6429 - 79ms/epoch - 20ms/step
Epoch 85/100
4/4 - 0s - loss: 0.0259 - acc: 1.0000 - val_loss: 1.5274 - val_acc: 0.5714 - 93ms/epoch - 23ms/step
Epoch 86/100
4/4 - 0s - loss: 0.0202 - acc: 1.0000 - val_loss: 1.5317 - val_acc: 0.5714 - 85ms/epoch - 21ms/step
Epoch 87/100
4/4 - 0s - loss: 0.0269 - acc: 1.0000 - val_loss: 1.6496 - val_acc: 0.5714 - 155ms/epoch - 39ms/step
Epoch 88/100
4/4 - 0s - loss: 0.0209 - acc: 1.0000 - val_loss: 1.6081 - val_acc: 0.5714 - 93ms/epoch - 23ms/step
Epoch 89/100
4/4 - 0s - loss: 0.0204 - acc: 1.0000 - val_loss: 1.5364 - val_acc: 0.5714 - 91ms/epoch - 23ms/step
Epoch 90/100
4/4 - 0s - loss: 0.0223 - acc: 1.0000 - val_loss: 1.4989 - val_acc: 0.5714 - 112ms/epoch - 28ms/step
Epoch 91/100
4/4 - 0s - loss: 0.0161 - acc: 1.0000 - val_loss: 1.3985 - val_acc: 0.6429 - 99ms/epoch - 25ms/step
Epoch 92/100
4/4 - 0s - loss: 0.0152 - acc: 1.0000 - val_loss: 1.2923 - val_acc: 0.6429 - 80ms/epoch - 20ms/step
Epoch 93/100
4/4 - 0s - loss: 0.0194 - acc: 1.0000 - val_loss: 1.2364 - val_acc: 0.6429 - 130ms/epoch - 32ms/step
Epoch 94/100
4/4 - 0s - loss: 0.0168 - acc: 1.0000 - val_loss: 1.2882 - val_acc: 0.6429 - 76ms/epoch - 19ms/step
Epoch 95/100
4/4 - 0s - loss: 0.0145 - acc: 1.0000 - val_loss: 1.3789 - val_acc: 0.6429 - 78ms/epoch - 20ms/step
Epoch 96/100
4/4 - 0s - loss: 0.0163 - acc: 1.0000 - val_loss: 1.4849 - val_acc: 0.5714 - 111ms/epoch - 28ms/step
Epoch 97/100
4/4 - 0s - loss: 0.0146 - acc: 1.0000 - val_loss: 1.5841 - val_acc: 0.5714 - 81ms/epoch - 20ms/step
Epoch 98/100
4/4 - 0s - loss: 0.0152 - acc: 1.0000 - val_loss: 1.6664 - val_acc: 0.5714 - 82ms/epoch - 21ms/step
Epoch 99/100
4/4 - 0s - loss: 0.0180 - acc: 1.0000 - val_loss: 1.7022 - val_acc: 0.5714 - 85ms/epoch - 21ms/step
Epoch 100/100
4/4 - 0s - loss: 0.0123 - acc: 1.0000 - val_loss: 1.6612 - val_acc: 0.5714 - 82ms/epoch - 21ms/step

In [ ]:
model_tte2 = Sequential()
model_tte2.add(LSTM(units=128, input_shape=(10, 50), return_sequences=True))
model_tte2.add(Dropout(0.3))
model_tte2.add(LSTM(units=64))
model_tte2.add(Dropout(0.2))
model_tte2.add(Dense(units=32, activation='relu'))
model_tte2.add(Dense(units=20, activation='relu'))
model_tte2.add(Dense(units=5, activation='relu'))

In [ ]:
model_tte2.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 lstm_8 (LSTM)               (None, 10, 128)           91648

 dropout_8 (Dropout)         (None, 10, 128)           0

 lstm_9 (LSTM)               (None, 64)                49408

 dropout_9 (Dropout)         (None, 64)                0

 dense_10 (Dense)            (None, 32)                2080

 dense_11 (Dense)            (None, 20)                660

 dense_12 (Dense)            (None, 5)                 105

=================================================================
Total params: 143901 (562.11 KB)
Trainable params: 143901 (562.11 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [ ]:
model_tte2.compile(optimizer='adam', loss=keras.losses.categorical_crossentropy, metrics=['acc'])

In [ ]:
history2 = model_tte2.fit(X_train, y_train, validation_split=0.1, verbose=2, batch_size=32, epochs=100)

Epoch 1/100
4/4 - 4s - loss: 11.0660 - acc: 0.1949 - val_loss: 6.4020 - val_acc: 0.2143 - 4s/epoch - 1s/step
Epoch 2/100
4/4 - 0s - loss: 9.8797 - acc: 0.1525 - val_loss: 6.4158 - val_acc: 0.4286 - 86ms/epoch - 21ms/step
Epoch 3/100
4/4 - 0s - loss: 9.8389 - acc: 0.2119 - val_loss: 6.4190 - val_acc: 0.2857 - 98ms/epoch - 25ms/step
Epoch 4/100
4/4 - 0s - loss: 9.8292 - acc: 0.2203 - val_loss: 6.4013 - val_acc: 0.2857 - 91ms/epoch - 23ms/step
Epoch 5/100
4/4 - 0s - loss: 9.8140 - acc: 0.2373 - val_loss: 6.3589 - val_acc: 0.4286 - 90ms/epoch - 23ms/step
Epoch 6/100
4/4 - 0s - loss: 9.7591 - acc: 0.2627 - val_loss: 6.2710 - val_acc: 0.5000 - 78ms/epoch - 19ms/step
Epoch 7/100
4/4 - 0s - loss: 9.7164 - acc: 0.2881 - val_loss: 6.1765 - val_acc: 0.3571 - 80ms/epoch - 20ms/step
Epoch 8/100
4/4 - 0s - loss: 9.6885 - acc: 0.3136 - val_loss: 6.1641 - val_acc: 0.3571 - 79ms/epoch - 20ms/step
Epoch 9/100
4/4 - 0s - loss: 9.5381 - acc: 0.3305 - val_loss: 6.1576 - val_acc: 0.3571 - 88ms/epoch - 22ms/step
Epoch 10/100
4/4 - 0s - loss: 7.3058 - acc: 0.2797 - val_loss: 5.4449 - val_acc: 0.2143 - 89ms/epoch - 22ms/step
Epoch 11/100
4/4 - 0s - loss: 5.2589 - acc: 0.2627 - val_loss: 5.5713 - val_acc: 0.0714 - 90ms/epoch - 23ms/step
Epoch 12/100
4/4 - 0s - loss: 5.2344 - acc: 0.2797 - val_loss: 5.6186 - val_acc: 0.0714 - 85ms/epoch - 21ms/step
Epoch 13/100
4/4 - 0s - loss: 4.7104 - acc: 0.3475 - val_loss: 2.2643 - val_acc: 0.0714 - 79ms/epoch - 20ms/step
Epoch 14/100
4/4 - 0s - loss: 2.4163 - acc: 0.3136 - val_loss: 1.9678 - val_acc: 0.0714 - 78ms/epoch - 20ms/step
Epoch 15/100
4/4 - 0s - loss: 2.2024 - acc: 0.3220 - val_loss: 1.9786 - val_acc: 0.0714 - 86ms/epoch - 21ms/step
Epoch 16/100
4/4 - 0s - loss: 1.5047 - acc: 0.3051 - val_loss: 1.8284 - val_acc: 0.0714 - 82ms/epoch - 21ms/step
Epoch 17/100
4/4 - 0s - loss: 1.5047 - acc: 0.3136 - val_loss: 1.7577 - val_acc: 0.0714 - 86ms/epoch - 21ms/step
Epoch 18/100
4/4 - 0s - loss: 1.4774 - acc: 0.3220 - val_loss: 1.7289 - val_acc: 0.0714 - 86ms/epoch - 21ms/step
Epoch 19/100
4/4 - 0s - loss: 1.4205 - acc: 0.3220 - val_loss: 1.7071 - val_acc: 0.0714 - 89ms/epoch - 22ms/step
Epoch 20/100
4/4 - 0s - loss: 1.4327 - acc: 0.3305 - val_loss: 1.6856 - val_acc: 0.0714 - 91ms/epoch - 23ms/step
Epoch 21/100
4/4 - 0s - loss: 1.3722 - acc: 0.3729 - val_loss: 1.6687 - val_acc: 0.0714 - 84ms/epoch - 21ms/step
Epoch 22/100
4/4 - 0s - loss: 1.3548 - acc: 0.3475 - val_loss: 1.6639 - val_acc: 0.0714 - 85ms/epoch - 21ms/step
Epoch 23/100
4/4 - 0s - loss: 1.3176 - acc: 0.3644 - val_loss: 1.7368 - val_acc: 0.1429 - 85ms/epoch - 21ms/step
Epoch 24/100
4/4 - 0s - loss: 1.2679 - acc: 0.3814 - val_loss: 2.4664 - val_acc: 0.1429 - 82ms/epoch - 20ms/step
Epoch 25/100
4/4 - 0s - loss: 1.3004 - acc: 0.3983 - val_loss: 2.3998 - val_acc: 0.0714 - 82ms/epoch - 21ms/step
Epoch 26/100
4/4 - 0s - loss: 1.1593 - acc: 0.4322 - val_loss: 2.3471 - val_acc: 0.1429 - 92ms/epoch - 23ms/step
Epoch 27/100
4/4 - 0s - loss: 1.3964 - acc: 0.3814 - val_loss: 2.3236 - val_acc: 0.1429 - 85ms/epoch - 21ms/step
Epoch 28/100
4/4 - 0s - loss: 1.1194 - acc: 0.4322 - val_loss: 2.3984 - val_acc: 0.1429 - 82ms/epoch - 20ms/step
Epoch 29/100
4/4 - 0s - loss: 1.3034 - acc: 0.4068 - val_loss: 2.4220 - val_acc: 0.1429 - 77ms/epoch - 19ms/step
Epoch 30/100
4/4 - 0s - loss: 1.2529 - acc: 0.3983 - val_loss: 2.3243 - val_acc: 0.1429 - 95ms/epoch - 24ms/step
Epoch 31/100
4/4 - 0s - loss: 1.4492 - acc: 0.4746 - val_loss: 2.2898 - val_acc: 0.1429 - 82ms/epoch - 20ms/step
Epoch 32/100
4/4 - 0s - loss: 1.2662 - acc: 0.4746 - val_loss: 2.3108 - val_acc: 0.2143 - 82ms/epoch - 20ms/step
Epoch 33/100
4/4 - 0s - loss: 1.1613 - acc: 0.5424 - val_loss: 1.4349 - val_acc: 0.2143 - 78ms/epoch - 20ms/step
Epoch 34/100
4/4 - 0s - loss: 0.9888 - acc: 0.5508 - val_loss: 2.1324 - val_acc: 0.4286 - 91ms/epoch - 23ms/step
Epoch 35/100
4/4 - 0s - loss: 1.6880 - acc: 0.5339 - val_loss: 2.2315 - val_acc: 0.2857 - 78ms/epoch - 20ms/step
Epoch 36/100
4/4 - 0s - loss: 1.0657 - acc: 0.6017 - val_loss: 2.2831 - val_acc: 0.1429 - 80ms/epoch - 20ms/step
Epoch 37/100
4/4 - 0s - loss: 1.1908 - acc: 0.5424 - val_loss: 2.3873 - val_acc: 0.1429 - 77ms/epoch - 19ms/step
Epoch 38/100
4/4 - 0s - loss: 2.1404 - acc: 0.3559 - val_loss: 3.5160 - val_acc: 0.2143 - 89ms/epoch - 22ms/step
Epoch 39/100
4/4 - 0s - loss: 2.1891 - acc: 0.3898 - val_loss: 2.3665 - val_acc: 0.1429 - 90ms/epoch - 22ms/step
Epoch 40/100
4/4 - 0s - loss: 1.0665 - acc: 0.4407 - val_loss: 3.6151 - val_acc: 0.1429 - 82ms/epoch - 20ms/step
Epoch 41/100
4/4 - 0s - loss: 2.7381 - acc: 0.3475 - val_loss: 2.5528 - val_acc: 0.1429 - 83ms/epoch - 21ms/step
Epoch 42/100
4/4 - 0s - loss: 1.5523 - acc: 0.4068 - val_loss: 1.4208 - val_acc: 0.0714 - 82ms/epoch - 20ms/step
Epoch 43/100
4/4 - 0s - loss: 1.1414 - acc: 0.4915 - val_loss: 1.3158 - val_acc: 0.2857 - 83ms/epoch - 21ms/step
Epoch 44/100
4/4 - 0s - loss: 1.1580 - acc: 0.4237 - val_loss: 1.3312 - val_acc: 0.2857 - 81ms/epoch - 20ms/step
Epoch 45/100
4/4 - 0s - loss: 1.1351 - acc: 0.5085 - val_loss: 1.3296 - val_acc: 0.2143 - 79ms/epoch - 20ms/step
Epoch 46/100
4/4 - 0s - loss: 1.0822 - acc: 0.5339 - val_loss: 1.3167 - val_acc: 0.2857 - 80ms/epoch - 20ms/step
Epoch 47/100
4/4 - 0s - loss: 1.1785 - acc: 0.5085 - val_loss: 1.3327 - val_acc: 0.4286 - 97ms/epoch - 24ms/step
Epoch 48/100
4/4 - 0s - loss: 1.1598 - acc: 0.5593 - val_loss: 2.1993 - val_acc: 0.2857 - 81ms/epoch - 20ms/step
Epoch 49/100
4/4 - 0s - loss: 0.9664 - acc: 0.5339 - val_loss: 2.0962 - val_acc: 0.4286 - 102ms/epoch - 25ms/step
Epoch 50/100
4/4 - 0s - loss: 1.1065 - acc: 0.5000 - val_loss: 2.0670 - val_acc: 0.3571 - 78ms/epoch - 19ms/step
Epoch 51/100
4/4 - 0s - loss: 1.0482 - acc: 0.5508 - val_loss: 2.0485 - val_acc: 0.3571 - 84ms/epoch - 21ms/step
Epoch 52/100
4/4 - 0s - loss: 0.8987 - acc: 0.6102 - val_loss: 2.0077 - val_acc: 0.4286 - 86ms/epoch - 21ms/step
Epoch 53/100
4/4 - 0s - loss: 0.8886 - acc: 0.5763 - val_loss: 2.0159 - val_acc: 0.3571 - 88ms/epoch - 22ms/step
Epoch 54/100
4/4 - 0s - loss: 0.8649 - acc: 0.6525 - val_loss: 2.0066 - val_acc: 0.3571 - 103ms/epoch - 26ms/step
Epoch 55/100
4/4 - 0s - loss: 0.8508 - acc: 0.6102 - val_loss: 1.9714 - val_acc: 0.4286 - 78ms/epoch - 20ms/step
Epoch 56/100
4/4 - 0s - loss: 0.7834 - acc: 0.6780 - val_loss: 1.9037 - val_acc: 0.5000 - 81ms/epoch - 20ms/step
Epoch 57/100
4/4 - 0s - loss: 1.0035 - acc: 0.6695 - val_loss: 1.8550 - val_acc: 0.6429 - 81ms/epoch - 20ms/step
Epoch 58/100
4/4 - 0s - loss: 0.9476 - acc: 0.6610 - val_loss: 2.2478 - val_acc: 0.2143 - 83ms/epoch - 21ms/step
Epoch 59/100
4/4 - 0s - loss: 1.0394 - acc: 0.4661 - val_loss: 2.2813 - val_acc: 0.1429 - 78ms/epoch - 19ms/step
Epoch 60/100
4/4 - 0s - loss: 1.0106 - acc: 0.4746 - val_loss: 1.4003 - val_acc: 0.1429 - 80ms/epoch - 20ms/step
Epoch 61/100
4/4 - 0s - loss: 1.0312 - acc: 0.4746 - val_loss: 1.3491 - val_acc: 0.1429 - 94ms/epoch - 23ms/step
Epoch 62/100
4/4 - 0s - loss: 0.9632 - acc: 0.4661 - val_loss: 1.3527 - val_acc: 0.1429 - 78ms/epoch - 20ms/step
Epoch 63/100
4/4 - 0s - loss: 0.9475 - acc: 0.4661 - val_loss: 1.3602 - val_acc: 0.1429 - 76ms/epoch - 19ms/step
Epoch 64/100
4/4 - 0s - loss: 0.9220 - acc: 0.5000 - val_loss: 1.3512 - val_acc: 0.0714 - 80ms/epoch - 20ms/step
Epoch 65/100
4/4 - 0s - loss: 0.9965 - acc: 0.5508 - val_loss: 1.1712 - val_acc: 0.0714 - 77ms/epoch - 19ms/step
Epoch 66/100
4/4 - 0s - loss: 0.8375 - acc: 0.6017 - val_loss: 1.0860 - val_acc: 0.2143 - 85ms/epoch - 21ms/step
Epoch 67/100
4/4 - 0s - loss: 0.8150 - acc: 0.6610 - val_loss: 1.0454 - val_acc: 0.2857 - 87ms/epoch - 22ms/step
Epoch 68/100
4/4 - 0s - loss: 0.7737 - acc: 0.7203 - val_loss: 1.0314 - val_acc: 0.2857 - 90ms/epoch - 22ms/step
Epoch 69/100
4/4 - 0s - loss: 0.7763 - acc: 0.7288 - val_loss: 0.9821 - val_acc: 0.3571 - 94ms/epoch - 23ms/step
Epoch 70/100
4/4 - 0s - loss: 0.7161 - acc: 0.7458 - val_loss: 0.9129 - val_acc: 0.5000 - 86ms/epoch - 21ms/step
Epoch 71/100
4/4 - 0s - loss: 0.8389 - acc: 0.7712 - val_loss: 0.8488 - val_acc: 0.5000 - 95ms/epoch - 24ms/step
Epoch 72/100
4/4 - 0s - loss: 0.7519 - acc: 0.6949 - val_loss: 0.9440 - val_acc: 0.3571 - 95ms/epoch - 24ms/step
Epoch 73/100
4/4 - 0s - loss: 0.8823 - acc: 0.7203 - val_loss: 0.9280 - val_acc: 0.4286 - 83ms/epoch - 21ms/step
Epoch 74/100
4/4 - 0s - loss: 0.9035 - acc: 0.7288 - val_loss: 0.9377 - val_acc: 0.4286 - 82ms/epoch - 20ms/step
Epoch 75/100
4/4 - 0s - loss: 0.7493 - acc: 0.7542 - val_loss: 0.9761 - val_acc: 0.4286 - 85ms/epoch - 21ms/step
Epoch 76/100
4/4 - 0s - loss: 0.7388 - acc: 0.7203 - val_loss: 0.9681 - val_acc: 0.4286 - 81ms/epoch - 20ms/step
Epoch 77/100
4/4 - 0s - loss: 0.7239 - acc: 0.7797 - val_loss: 0.9383 - val_acc: 0.5000 - 81ms/epoch - 20ms/step
Epoch 78/100
4/4 - 0s - loss: 0.6888 - acc: 0.7119 - val_loss: 0.9249 - val_acc: 0.5000 - 91ms/epoch - 23ms/step
Epoch 79/100
4/4 - 0s - loss: 0.6518 - acc: 0.7203 - val_loss: 1.8131 - val_acc: 0.5714 - 90ms/epoch - 22ms/step
Epoch 80/100
4/4 - 0s - loss: 0.6381 - acc: 0.6949 - val_loss: 1.8143 - val_acc: 0.6429 - 85ms/epoch - 21ms/step
Epoch 81/100
4/4 - 0s - loss: 0.5900 - acc: 0.7542 - val_loss: 1.8356 - val_acc: 0.5714 - 85ms/epoch - 21ms/step
Epoch 82/100
4/4 - 0s - loss: 0.5849 - acc: 0.7034 - val_loss: 1.8695 - val_acc: 0.5714 - 84ms/epoch - 21ms/step
Epoch 83/100
4/4 - 0s - loss: 0.5739 - acc: 0.7203 - val_loss: 1.9406 - val_acc: 0.5714 - 83ms/epoch - 21ms/step
Epoch 84/100
4/4 - 0s - loss: 0.5535 - acc: 0.7034 - val_loss: 2.0603 - val_acc: 0.5000 - 92ms/epoch - 23ms/step
Epoch 85/100
4/4 - 0s - loss: 0.5191 - acc: 0.7203 - val_loss: 2.9486 - val_acc: 0.5714 - 87ms/epoch - 22ms/step
Epoch 86/100
4/4 - 0s - loss: 0.6006 - acc: 0.7119 - val_loss: 2.0001 - val_acc: 0.6429 - 79ms/epoch - 20ms/step
Epoch 87/100
4/4 - 0s - loss: 1.2044 - acc: 0.6525 - val_loss: 3.1602 - val_acc: 0.4286 - 80ms/epoch - 20ms/step
Epoch 88/100
4/4 - 0s - loss: 1.4537 - acc: 0.6695 - val_loss: 3.0950 - val_acc: 0.4286 - 80ms/epoch - 20ms/step
Epoch 89/100
4/4 - 0s - loss: 1.2096 - acc: 0.6271 - val_loss: 2.0999 - val_acc: 0.3571 - 87ms/epoch - 22ms/step
Epoch 90/100
4/4 - 0s - loss: 1.1471 - acc: 0.7034 - val_loss: 0.9714 - val_acc: 0.4286 - 116ms/epoch - 29ms/step
Epoch 91/100
4/4 - 0s - loss: 0.8546 - acc: 0.7542 - val_loss: 1.9694 - val_acc: 0.5714 - 121ms/epoch - 30ms/step
Epoch 92/100
4/4 - 0s - loss: nan - acc: 0.6949 - val_loss: nan - val_acc: 0.2143 - 137ms/epoch - 34ms/step
Epoch 93/100
4/4 - 0s - loss: nan - acc: 0.1610 - val_loss: nan - val_acc: 0.2143 - 114ms/epoch - 28ms/step
Epoch 94/100
4/4 - 0s - loss: nan - acc: 0.1610 - val_loss: nan - val_acc: 0.2143 - 137ms/epoch - 34ms/step
Epoch 95/100
4/4 - 0s - loss: nan - acc: 0.1610 - val_loss: nan - val_acc: 0.2143 - 119ms/epoch - 30ms/step
Epoch 96/100
4/4 - 0s - loss: nan - acc: 0.1610 - val_loss: nan - val_acc: 0.2143 - 134ms/epoch - 34ms/step
Epoch 97/100
4/4 - 0s - loss: nan - acc: 0.1610 - val_loss: nan - val_acc: 0.2143 - 144ms/epoch - 36ms/step
Epoch 98/100
4/4 - 0s - loss: nan - acc: 0.1610 - val_loss: nan - val_acc: 0.2143 - 147ms/epoch - 37ms/step
Epoch 99/100
4/4 - 0s - loss: nan - acc: 0.1610 - val_loss: nan - val_acc: 0.2143 - 120ms/epoch - 30ms/step
Epoch 100/100
4/4 - 0s - loss: nan - acc: 0.1610 - val_loss: nan - val_acc: 0.2143 - 117ms/epoch - 29ms/step

In [ ]:
model_tte3 = Sequential()
model_tte3.add(LSTM(units=128, input_shape=(10, 50), return_sequences=True))
model_tte3.add(Dropout(0.3))
model_tte3.add(LSTM(units=64))
model_tte3.add(Dropout(0.2))
model_tte3.add(Dense(units=32, activation='relu'))
model_tte3.add(Dense(units=20, activation='relu'))
model_tte3.add(Dense(units=5, activation='softmax'))

In [ ]:
model_tte3.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 lstm_10 (LSTM)              (None, 10, 128)           91648

 dropout_10 (Dropout)        (None, 10, 128)           0

 lstm_11 (LSTM)              (None, 64)                49408

 dropout_11 (Dropout)        (None, 64)                0

 dense_13 (Dense)            (None, 32)                2080

 dense_14 (Dense)            (None, 20)                660

 dense_15 (Dense)            (None, 5)                 105

=================================================================
Total params: 143901 (562.11 KB)
Trainable params: 143901 (562.11 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [ ]:
model_tte3.compile(optimizer='adam', loss=keras.losses.categorical_crossentropy, metrics=['acc'])

In [ ]:
history3 = model_tte3.fit(X_train, y_train, validation_split=0.1, verbose=2, batch_size=32, epochs=100)

Epoch 1/100
4/4 - 4s - loss: 1.6024 - acc: 0.2712 - val_loss: 1.6413 - val_acc: 0.0714 - 4s/epoch - 885ms/step
Epoch 2/100
4/4 - 0s - loss: 1.5616 - acc: 0.3136 - val_loss: 1.7130 - val_acc: 0.0714 - 77ms/epoch - 19ms/step
Epoch 3/100
4/4 - 0s - loss: 1.5349 - acc: 0.3136 - val_loss: 1.7181 - val_acc: 0.0714 - 79ms/epoch - 20ms/step
Epoch 4/100
4/4 - 0s - loss: 1.5013 - acc: 0.3220 - val_loss: 1.6790 - val_acc: 0.0714 - 79ms/epoch - 20ms/step
Epoch 5/100
4/4 - 0s - loss: 1.4594 - acc: 0.3644 - val_loss: 1.6537 - val_acc: 0.1429 - 84ms/epoch - 21ms/step
Epoch 6/100
4/4 - 0s - loss: 1.3895 - acc: 0.4153 - val_loss: 1.6859 - val_acc: 0.1429 - 85ms/epoch - 21ms/step
Epoch 7/100
4/4 - 0s - loss: 1.3023 - acc: 0.4407 - val_loss: 1.5761 - val_acc: 0.2143 - 78ms/epoch - 20ms/step
Epoch 8/100
4/4 - 0s - loss: 1.2198 - acc: 0.5169 - val_loss: 1.5198 - val_acc: 0.2857 - 83ms/epoch - 21ms/step
Epoch 9/100
4/4 - 0s - loss: 1.0703 - acc: 0.5932 - val_loss: 1.2599 - val_acc: 0.6429 - 87ms/epoch - 22ms/step
Epoch 10/100
4/4 - 0s - loss: 0.9864 - acc: 0.6610 - val_loss: 1.5787 - val_acc: 0.5000 - 78ms/epoch - 19ms/step
Epoch 11/100
4/4 - 0s - loss: 0.8209 - acc: 0.6780 - val_loss: 0.9564 - val_acc: 0.6429 - 86ms/epoch - 21ms/step
Epoch 12/100
4/4 - 0s - loss: 0.8019 - acc: 0.7458 - val_loss: 1.5550 - val_acc: 0.4286 - 81ms/epoch - 20ms/step
Epoch 13/100
4/4 - 0s - loss: 0.7273 - acc: 0.7203 - val_loss: 1.1484 - val_acc: 0.5714 - 86ms/epoch - 21ms/step
Epoch 14/100
4/4 - 0s - loss: 0.5947 - acc: 0.8051 - val_loss: 1.5410 - val_acc: 0.5000 - 80ms/epoch - 20ms/step
Epoch 15/100
4/4 - 0s - loss: 0.7347 - acc: 0.7542 - val_loss: 1.0713 - val_acc: 0.5714 - 82ms/epoch - 21ms/step
Epoch 16/100
4/4 - 0s - loss: 0.5113 - acc: 0.8051 - val_loss: 1.4853 - val_acc: 0.5000 - 81ms/epoch - 20ms/step
Epoch 17/100
4/4 - 0s - loss: 0.4666 - acc: 0.8644 - val_loss: 1.0097 - val_acc: 0.7143 - 83ms/epoch - 21ms/step
Epoch 18/100
4/4 - 0s - loss: 0.3862 - acc: 0.8898 - val_loss: 1.2313 - val_acc: 0.6429 - 86ms/epoch - 21ms/step
Epoch 19/100
4/4 - 0s - loss: 0.3945 - acc: 0.8644 - val_loss: 1.4160 - val_acc: 0.5000 - 81ms/epoch - 20ms/step
Epoch 20/100
4/4 - 0s - loss: 0.3332 - acc: 0.8729 - val_loss: 1.0764 - val_acc: 0.6429 - 78ms/epoch - 19ms/step
Epoch 21/100
4/4 - 0s - loss: 0.3079 - acc: 0.9068 - val_loss: 1.2086 - val_acc: 0.6429 - 82ms/epoch - 21ms/step
Epoch 22/100
4/4 - 0s - loss: 0.2946 - acc: 0.9153 - val_loss: 1.3529 - val_acc: 0.5714 - 81ms/epoch - 20ms/step
Epoch 23/100
4/4 - 0s - loss: 0.2852 - acc: 0.9237 - val_loss: 1.1636 - val_acc: 0.5000 - 78ms/epoch - 19ms/step
Epoch 24/100
4/4 - 0s - loss: 0.3696 - acc: 0.8898 - val_loss: 0.7981 - val_acc: 0.6429 - 89ms/epoch - 22ms/step
Epoch 25/100
4/4 - 0s - loss: 0.3444 - acc: 0.8729 - val_loss: 1.3848 - val_acc: 0.5714 - 89ms/epoch - 22ms/step
Epoch 26/100
4/4 - 0s - loss: 0.2774 - acc: 0.8983 - val_loss: 1.8511 - val_acc: 0.4286 - 96ms/epoch - 24ms/step
Epoch 27/100
4/4 - 0s - loss: 0.2094 - acc: 0.9492 - val_loss: 0.7359 - val_acc: 0.7857 - 80ms/epoch - 20ms/step
Epoch 28/100
4/4 - 0s - loss: 0.2707 - acc: 0.8983 - val_loss: 1.2880 - val_acc: 0.5714 - 81ms/epoch - 20ms/step
Epoch 29/100
4/4 - 0s - loss: 0.1573 - acc: 0.9661 - val_loss: 1.7001 - val_acc: 0.4286 - 80ms/epoch - 20ms/step
Epoch 30/100
4/4 - 0s - loss: 0.2134 - acc: 0.9153 - val_loss: 0.9886 - val_acc: 0.6429 - 79ms/epoch - 20ms/step
Epoch 31/100
4/4 - 0s - loss: 0.1189 - acc: 0.9746 - val_loss: 1.0789 - val_acc: 0.5000 - 76ms/epoch - 19ms/step
Epoch 32/100
4/4 - 0s - loss: 0.1426 - acc: 0.9576 - val_loss: 0.7770 - val_acc: 0.7857 - 83ms/epoch - 21ms/step
Epoch 33/100
4/4 - 0s - loss: 0.1521 - acc: 0.9407 - val_loss: 1.6907 - val_acc: 0.5000 - 84ms/epoch - 21ms/step
Epoch 34/100
4/4 - 0s - loss: 0.2165 - acc: 0.9068 - val_loss: 0.5694 - val_acc: 0.7143 - 84ms/epoch - 21ms/step
Epoch 35/100
4/4 - 0s - loss: 0.1445 - acc: 0.9576 - val_loss: 0.5988 - val_acc: 0.7857 - 80ms/epoch - 20ms/step
Epoch 36/100
4/4 - 0s - loss: 0.0813 - acc: 0.9831 - val_loss: 2.0975 - val_acc: 0.4286 - 91ms/epoch - 23ms/step
Epoch 37/100
4/4 - 0s - loss: 0.1463 - acc: 0.9576 - val_loss: 0.2519 - val_acc: 0.8571 - 80ms/epoch - 20ms/step
Epoch 38/100
4/4 - 0s - loss: 0.1180 - acc: 0.9407 - val_loss: 1.0835 - val_acc: 0.6429 - 85ms/epoch - 21ms/step
Epoch 39/100
4/4 - 0s - loss: 0.1176 - acc: 0.9661 - val_loss: 1.4307 - val_acc: 0.5714 - 82ms/epoch - 21ms/step
Epoch 40/100
4/4 - 0s - loss: 0.0627 - acc: 0.9831 - val_loss: 0.4438 - val_acc: 0.7857 - 85ms/epoch - 21ms/step
Epoch 41/100
4/4 - 0s - loss: 0.0840 - acc: 0.9746 - val_loss: 0.7172 - val_acc: 0.7143 - 88ms/epoch - 22ms/step
Epoch 42/100
4/4 - 0s - loss: 0.0599 - acc: 0.9831 - val_loss: 1.3344 - val_acc: 0.5000 - 84ms/epoch - 21ms/step
Epoch 43/100
4/4 - 0s - loss: 0.0477 - acc: 0.9915 - val_loss: 1.1030 - val_acc: 0.5714 - 100ms/epoch - 25ms/step
Epoch 44/100
4/4 - 0s - loss: 0.0422 - acc: 1.0000 - val_loss: 0.9079 - val_acc: 0.6429 - 88ms/epoch - 22ms/step
Epoch 45/100
4/4 - 0s - loss: 0.0343 - acc: 1.0000 - val_loss: 0.7305 - val_acc: 0.7143 - 84ms/epoch - 21ms/step
Epoch 46/100
4/4 - 0s - loss: 0.0310 - acc: 1.0000 - val_loss: 1.4254 - val_acc: 0.5714 - 78ms/epoch - 19ms/step
Epoch 47/100
4/4 - 0s - loss: 0.0231 - acc: 1.0000 - val_loss: 1.6021 - val_acc: 0.5714 - 84ms/epoch - 21ms/step
Epoch 48/100
4/4 - 0s - loss: 0.0197 - acc: 1.0000 - val_loss: 0.8635 - val_acc: 0.7857 - 87ms/epoch - 22ms/step
Epoch 49/100
4/4 - 0s - loss: 0.0191 - acc: 0.9915 - val_loss: 0.6440 - val_acc: 0.8571 - 79ms/epoch - 20ms/step
Epoch 50/100
4/4 - 0s - loss: 0.0189 - acc: 1.0000 - val_loss: 0.8472 - val_acc: 0.7143 - 78ms/epoch - 19ms/step
Epoch 51/100
4/4 - 0s - loss: 0.0099 - acc: 1.0000 - val_loss: 1.1420 - val_acc: 0.7143 - 78ms/epoch - 20ms/step
Epoch 52/100
4/4 - 0s - loss: 0.0116 - acc: 1.0000 - val_loss: 1.3869 - val_acc: 0.7143 - 80ms/epoch - 20ms/step
Epoch 53/100
4/4 - 0s - loss: 0.0183 - acc: 1.0000 - val_loss: 1.3879 - val_acc: 0.6429 - 81ms/epoch - 20ms/step
Epoch 54/100
4/4 - 0s - loss: 0.0087 - acc: 1.0000 - val_loss: 1.4409 - val_acc: 0.5714 - 79ms/epoch - 20ms/step
Epoch 55/100
4/4 - 0s - loss: 0.0097 - acc: 1.0000 - val_loss: 1.1527 - val_acc: 0.6429 - 82ms/epoch - 20ms/step
Epoch 56/100
4/4 - 0s - loss: 0.0088 - acc: 1.0000 - val_loss: 0.8287 - val_acc: 0.7143 - 78ms/epoch - 19ms/step
Epoch 57/100
4/4 - 0s - loss: 0.0095 - acc: 1.0000 - val_loss: 0.7387 - val_acc: 0.7857 - 86ms/epoch - 22ms/step
Epoch 58/100
4/4 - 0s - loss: 0.0086 - acc: 1.0000 - val_loss: 0.8177 - val_acc: 0.7143 - 77ms/epoch - 19ms/step
Epoch 59/100
4/4 - 0s - loss: 0.0049 - acc: 1.0000 - val_loss: 1.0318 - val_acc: 0.7143 - 77ms/epoch - 19ms/step
Epoch 60/100
4/4 - 0s - loss: 0.0050 - acc: 1.0000 - val_loss: 1.1676 - val_acc: 0.7143 - 87ms/epoch - 22ms/step
Epoch 61/100
4/4 - 0s - loss: 0.0056 - acc: 1.0000 - val_loss: 1.1339 - val_acc: 0.6429 - 84ms/epoch - 21ms/step
Epoch 62/100
4/4 - 0s - loss: 0.0091 - acc: 1.0000 - val_loss: 1.9401 - val_acc: 0.5000 - 78ms/epoch - 20ms/step
Epoch 63/100
4/4 - 0s - loss: 0.0304 - acc: 0.9915 - val_loss: 1.4401 - val_acc: 0.5714 - 90ms/epoch - 22ms/step
Epoch 64/100
4/4 - 0s - loss: 0.0258 - acc: 0.9915 - val_loss: 0.9667 - val_acc: 0.6429 - 87ms/epoch - 22ms/step
Epoch 65/100
4/4 - 0s - loss: 0.0165 - acc: 0.9915 - val_loss: 0.9840 - val_acc: 0.6429 - 84ms/epoch - 21ms/step
Epoch 66/100
4/4 - 0s - loss: 0.0125 - acc: 1.0000 - val_loss: 1.0835 - val_acc: 0.5714 - 80ms/epoch - 20ms/step
Epoch 67/100
4/4 - 0s - loss: 0.0096 - acc: 1.0000 - val_loss: 0.7130 - val_acc: 0.7143 - 82ms/epoch - 21ms/step
Epoch 68/100
4/4 - 0s - loss: 0.0051 - acc: 1.0000 - val_loss: 0.6981 - val_acc: 0.6429 - 79ms/epoch - 20ms/step
Epoch 69/100
4/4 - 0s - loss: 0.0096 - acc: 1.0000 - val_loss: 0.4252 - val_acc: 0.8571 - 80ms/epoch - 20ms/step
Epoch 70/100
4/4 - 0s - loss: 0.0061 - acc: 1.0000 - val_loss: 0.5890 - val_acc: 0.8571 - 77ms/epoch - 19ms/step
Epoch 71/100
4/4 - 0s - loss: 0.0042 - acc: 1.0000 - val_loss: 0.9377 - val_acc: 0.7143 - 82ms/epoch - 21ms/step
Epoch 72/100
4/4 - 0s - loss: 0.0033 - acc: 1.0000 - val_loss: 1.2028 - val_acc: 0.7143 - 87ms/epoch - 22ms/step
Epoch 73/100
4/4 - 0s - loss: 0.0033 - acc: 1.0000 - val_loss: 1.2985 - val_acc: 0.7143 - 81ms/epoch - 20ms/step
Epoch 74/100
4/4 - 0s - loss: 0.0037 - acc: 1.0000 - val_loss: 1.3067 - val_acc: 0.6429 - 77ms/epoch - 19ms/step
Epoch 75/100
4/4 - 0s - loss: 0.0039 - acc: 1.0000 - val_loss: 1.1564 - val_acc: 0.7143 - 80ms/epoch - 20ms/step
Epoch 76/100
4/4 - 0s - loss: 0.0028 - acc: 1.0000 - val_loss: 0.9762 - val_acc: 0.7143 - 81ms/epoch - 20ms/step
Epoch 77/100
4/4 - 0s - loss: 0.0025 - acc: 1.0000 - val_loss: 0.8761 - val_acc: 0.7143 - 82ms/epoch - 21ms/step
Epoch 78/100
4/4 - 0s - loss: 0.0027 - acc: 1.0000 - val_loss: 0.8738 - val_acc: 0.7857 - 132ms/epoch - 33ms/step
Epoch 79/100
4/4 - 0s - loss: 0.0029 - acc: 1.0000 - val_loss: 0.8990 - val_acc: 0.7857 - 111ms/epoch - 28ms/step
Epoch 80/100
4/4 - 0s - loss: 0.0023 - acc: 1.0000 - val_loss: 0.9645 - val_acc: 0.7857 - 134ms/epoch - 33ms/step
Epoch 81/100
4/4 - 0s - loss: 0.0025 - acc: 1.0000 - val_loss: 1.0163 - val_acc: 0.6429 - 123ms/epoch - 31ms/step
Epoch 82/100
4/4 - 0s - loss: 0.0030 - acc: 1.0000 - val_loss: 1.0592 - val_acc: 0.6429 - 139ms/epoch - 35ms/step
Epoch 83/100
4/4 - 0s - loss: 0.0044 - acc: 1.0000 - val_loss: 1.1975 - val_acc: 0.6429 - 107ms/epoch - 27ms/step
Epoch 84/100
4/4 - 0s - loss: 0.0026 - acc: 1.0000 - val_loss: 1.6202 - val_acc: 0.5714 - 138ms/epoch - 34ms/step
Epoch 85/100
4/4 - 0s - loss: 0.0026 - acc: 1.0000 - val_loss: 1.7447 - val_acc: 0.5714 - 111ms/epoch - 28ms/step
Epoch 86/100
4/4 - 0s - loss: 0.0024 - acc: 1.0000 - val_loss: 1.7585 - val_acc: 0.5714 - 120ms/epoch - 30ms/step
Epoch 87/100
4/4 - 0s - loss: 0.0023 - acc: 1.0000 - val_loss: 1.6415 - val_acc: 0.5714 - 133ms/epoch - 33ms/step
Epoch 88/100
4/4 - 0s - loss: 0.0055 - acc: 1.0000 - val_loss: 1.3670 - val_acc: 0.5714 - 109ms/epoch - 27ms/step
Epoch 89/100
4/4 - 0s - loss: 0.0021 - acc: 1.0000 - val_loss: 1.1016 - val_acc: 0.7143 - 123ms/epoch - 31ms/step
Epoch 90/100
4/4 - 0s - loss: 0.0023 - acc: 1.0000 - val_loss: 1.0083 - val_acc: 0.7143 - 123ms/epoch - 31ms/step
Epoch 91/100
4/4 - 0s - loss: 0.0021 - acc: 1.0000 - val_loss: 0.9356 - val_acc: 0.7143 - 126ms/epoch - 31ms/step
Epoch 92/100
4/4 - 0s - loss: 0.0018 - acc: 1.0000 - val_loss: 0.8837 - val_acc: 0.7143 - 125ms/epoch - 31ms/step
Epoch 93/100
4/4 - 0s - loss: 0.0022 - acc: 1.0000 - val_loss: 0.8653 - val_acc: 0.7857 - 112ms/epoch - 28ms/step
Epoch 94/100
4/4 - 0s - loss: 0.0017 - acc: 1.0000 - val_loss: 0.8739 - val_acc: 0.7857 - 133ms/epoch - 33ms/step
Epoch 95/100
4/4 - 0s - loss: 0.0015 - acc: 1.0000 - val_loss: 0.8915 - val_acc: 0.7857 - 106ms/epoch - 27ms/step
Epoch 96/100
4/4 - 0s - loss: 0.0028 - acc: 1.0000 - val_loss: 0.9724 - val_acc: 0.7143 - 80ms/epoch - 20ms/step
Epoch 97/100
4/4 - 0s - loss: 0.0016 - acc: 1.0000 - val_loss: 1.1304 - val_acc: 0.6429 - 79ms/epoch - 20ms/step
Epoch 98/100
4/4 - 0s - loss: 0.0014 - acc: 1.0000 - val_loss: 1.2039 - val_acc: 0.6429 - 82ms/epoch - 20ms/step
Epoch 99/100
4/4 - 0s - loss: 0.0023 - acc: 1.0000 - val_loss: 1.2112 - val_acc: 0.6429 - 102ms/epoch - 26ms/step
Epoch 100/100
4/4 - 0s - loss: 0.0018 - acc: 1.0000 - val_loss: 1.3098 - val_acc: 0.5714 - 85ms/epoch - 21ms/step

In [ ]:
test_data = pd.read_csv("/content/test_emoji.csv", header=None)

In [ ]:
test_data.head()

                             0  1
0              I want to eat\t  4
1          he did not answer\t  3
2   he got a very nice raise\t  2
3  she got me a nice present\t  2
4   ha ha ha it was so funny\t  2

In [ ]:
# preprocessing test data
test_data[0] = test_data[0].apply(lambda x:x[:-1])
X_test = test_data[0].values
y_test = test_data[1].values

In [ ]:
X_test = get_emb_data(X_test, 10)
y_test = to_categorical(y_test)

In [ ]:
model_tte3.evaluate(X_test, y_test)[1]*100

2/2 [==============================] - 0s 7ms/step - loss: 1.7044 - acc: 0.7321

73.21428656578064

In [ ]:
predicted = model_tte3.predict(X_test)

2/2 [==============================] - 1s 7ms/step

In [ ]:
classes = np.argmax(predicted,axis=1)

In [ ]:
for t in range(len(classes)):
    print(test_data[0].iloc[t])
    print("Predictions: ", emoji.emojize(emoji_mapping[str(classes[t])]))
    print('Actual: ', emoji.emojize(emoji_mapping[str(test_data[1].iloc[t])]))

I want to eat
Predictions:  😋
Actual:  😋
he did not answer
Predictions:  😠
Actual:  😠
he got a very nice raise
Predictions:  💓
Actual:  😁
she got me a nice present
Predictions:  💓
Actual:  😁
ha ha ha it was so funny
Predictions:  😁
Actual:  😁
he is a good friend
Predictions:  😁
Actual:  😁
I am upset
Predictions:  😠
Actual:  😠
We had such a lovely dinner tonight
Predictions:  😁
Actual:  😁
where is the food
Predictions:  😋
Actual:  😋
Stop making this joke ha ha ha
Predictions:  😁
Actual:  😁
where is the ball
Predictions:  ⚾
Actual:  ⚾
work is hard
Predictions:  😁
Actual:  😠
This girl is messing with me
Predictions:  😠
Actual:  😠
are you seriou
Predictions:  😠
Actual:  😠
Let us go play baseball
Predictions:  ⚾
Actual:  ⚾
This stupid grader is not working
Predictions:  😠
Actual:  😠
work is horrible
Predictions:  😁
Actual:  😠
Congratulation for having a baby
Predictions:  😁
Actual:  😁
stop pissing me of
Predictions:  😠
Actual:  😠
any suggestions for dinner
Predictions:  😁
Actual:  😋
I love taking breaks
Predictions:  😠
Actual:  💓
you brighten my day
Predictions:  💓
Actual:  😁
I boiled rice
Predictions:  😋
Actual:  😋
she is a bully
Predictions:  😁
Actual:  😠
Why are you feeling bad
Predictions:  😠
Actual:  😠
I am upset
Predictions:  😠
Actual:  😠
give me the bal
Predictions:  😁
Actual:  ⚾
My grandmother is the love of my life
Predictions:  💓
Actual:  💓
enjoy your gam
Predictions:  😋
Actual:  ⚾
valentine day is near
Predictions:  😁
Actual:  😁
I miss you so much
Predictions:  💓
Actual:  💓
throw the ball
Predictions:  ⚾
Actual:  ⚾
My life is so boring
Predictions:  😠
Actual:  😠
she said yes
Predictions:  😁
Actual:  😁
will you be my valentine
Predictions:  💓
Actual:  😁
he can pitch really well
Predictions:  ⚾
Actual:  ⚾
dance with me
Predictions:  😁
Actual:  😁
I am hungr
Predictions:  😠
Actual:  😋
See you at the restaurant
Predictions:  😋
Actual:  😋
I like to laugh
Predictions:  😁
Actual:  😁
I will  ru
Predictions:  ⚾
Actual:  ⚾
I like your jacket
Predictions:  💓
Actual:  💓
i miss her
Predictions:  💓
Actual:  💓
what is your favorite baseball game
Predictions:  ⚾
Actual:  ⚾
Good job
Predictions:  😁
Actual:  😁
I love you to the stars and back
Predictions:  😁
Actual:  💓
What you did was awesome
Predictions:  😁
Actual:  😁
ha ha ha lol
Predictions:  😁
Actual:  😁
I do not want to joke
Predictions:  😠
Actual:  😠
go away
Predictions:  😋
Actual:  😠
yesterday we lost again
Predictions:  😠
Actual:  😠
family is all I have
Predictions:  💓
Actual:  💓
you are failing this exercise
Predictions:  😠
Actual:  😠
Good joke
Predictions:  😁
Actual:  😁
You deserve this nice prize
Predictions:  😁
Actual:  😁
I did not have breakfast
Predictions:  😠
Actual:  😋

# with VIT

In [ ]:
sample = np.array([caption])
sample = get_emb_data(sample, 10)

In [ ]:
pr = model_tte3.predict(sample)

1/1 [==============================] - 0s 19ms/step

In [ ]:
result = np.argmax(pr,axis=1)

In [ ]:
emoji.emojize(emoji_mapping[str(result[0])])

'💓'